# Generated by Django 2.2.16 on 2020-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
