# Generated by Django 2.2.16 on 2020-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberlist', '0002_auto_20200908_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='static',
            field=models.ImageField(blank=True, upload_to='boxinggloves'),
        ),
    ]
