# Generated by Django 2.2.16 on 2020-09-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberlist', '0003_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='static',
        ),
    ]
